# Generated by Django 3.0.6 on 2020-05-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
