# Generated by Django 3.0.6 on 2020-05-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20200519_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joined_on',
            field=models.DateTimeField(auto_now_add=True, db_column='user_joined_on'),
        ),
    ]
