# Generated by Django 3.0.6 on 2020-05-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20200519_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, db_column='user_bio', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='fcoin',
            field=models.CharField(db_column='user_fcoin', default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.CharField(blank=True, db_column='user_interests', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, db_column='user_profile_image', upload_to=''),
        ),
    ]
