# Generated by Django 3.0.6 on 2020-05-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20200519_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
