# Generated by Django 3.0.6 on 2020-05-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20200520_0039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intro_video',
            old_name='intro_id',
            new_name='intro_video_id',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='bookmark',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
